name: stochastic_games
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - cudatoolkit-dev
  - cudnn
  - networkx
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - numba
  - jupyterlab
  - pip:
      - tensorflow>=2.11.0
      - tensorrt>=8.0.0
      - tensorflow_probability
      - tensorflow_gnn
